services:
  drone:
    build:
      context: .
      dockerfile: Dockerfile
    image: drone:latest
    networks:
      fleet_net:
        ipv4_address: 192.168.100.130
    container_name: drone
    volumes:
      - ./Logs:/home/Drone/Logs

networks:
  fleet_net:
    external: true