services:
  fleet_manager:
    build:
      context: .
      dockerfile: Dockerfile
    image: fleet_manager:latest
    networks:
      fleet_net:
        ipv4_address: 192.168.100.140
    container_name: fleet_manager
    volumes:
      - ./Logs:/home/Fleet/Logs

networks:
  fleet_net:
    external: true