services:
  fleet_manager:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    image: fleet_manager:latest
    container_name: fleet_manager
    volumes:
      - ./Logs:/home/Fleet/Logs
