services:
  drone_copy:
    build:
      context: .
      dockerfile: Dockerfile
    image: drone_copy:latest
    networks:
      fleet_net:
        ipv4_address: 192.168.100.129
    container_name: drone_copy
    volumes:
      - ./Logs:/home/Drone/Logs
    env_file:
      - .env

networks:
  fleet_net:
    external: true